// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieJobs.Data;

namespace PieJobs.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211005174231_AddedLogs")]
    partial class AddedLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PieJobs.Data.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduleDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobDefinitionId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("PieJobs.Data.JobDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobDefinitions");
                });

            modelBuilder.Entity("PieJobs.Data.LogLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("LogLines");
                });

            modelBuilder.Entity("PieJobs.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiToken = "7f0d9265-1265-4167-890b-1dfbbb05f93e",
                            DisplayName = "Admin",
                            Password = "5Mt/I3P5RbZrSXyI/k5FVz+lTL+ffWO+|10000|NbHfoOfFCJLUZCrSGZ/+VvMvNFB258cp",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("PieJobs.Data.Job", b =>
                {
                    b.HasOne("PieJobs.Data.JobDefinition", "JobDefinition")
                        .WithMany()
                        .HasForeignKey("JobDefinitionId");

                    b.Navigation("JobDefinition");
                });

            modelBuilder.Entity("PieJobs.Data.LogLine", b =>
                {
                    b.HasOne("PieJobs.Data.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
